services:

  db:
    image: postgres:alpine
    hostname: db
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123pswd
      POSTGRES_DB: analytics

  app:
    build: ./app-back/
    hostname: api
    ports:
      - 3012:3012
    depends_on:
      - db
    links:
      - "db:database"
  
  front:
    build: ./app-front/
    ports:
      - 3000:3000
    depends_on:
      - app
    links:
      - "app:api_app"
  